# Generated by Django 4.2.5 on 2023-09-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=155)),
                ('id_tg', models.IntegerField()),
                ('lang', models.CharField(max_length=3)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branches')),
            ],
            options={
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branches')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workers')),
            ],
            options={
                'verbose_name_plural': 'Docs',
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_num', models.CharField(max_length=100)),
                ('sum', models.CharField(max_length=155)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branches')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workers')),
            ],
            options={
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
