# Generated by Django 4.2.5 on 2023-09-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='lang',
        ),
    ]
