# Generated by Django 4.2.5 on 2023-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_workers_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='checks',
            name='check_num',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='doc_num',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='id_tg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
