# Generated by Django 4.2.5 on 2023-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branches_name_alter_checks_check_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
