# Generated by Django 4.2.5 on 2023-09-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_checks_date_alter_docs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.workers'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.workers'),
        ),
    ]
