# Generated by Django 4.2.5 on 2023-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_checks_worker_alter_docs_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='worker',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='core.workers'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='worker',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='core.workers'),
        ),
    ]
